### ISSUE TITLE
test hangs

### ISSUE THREAD

**Issue by rootsical** [nodaguti/gulp-electron-mocha#1]
nice idea! unfortunately my test is hanging at the moment and i have to shut it down with <kbd>CTRL C</kbd>. this is my code:  
```javascript
import electronMocha from 'gulp-electron-mocha';

gulp.task('test:renderer', function(){
  return gulp.src('test/renderer', { read: false })
    .pipe(electronMocha({
      electronMocha: {
        renderer: true,
        'no-timeouts': true,
        require: 'babel-core/register'
      }
    }));
});
```
electron spits out:
`(electron) loadUrl is deprecated. Use loadURL instead.`
but i don't know what the actual problem is..

with the same options, the latest version of electron-mocha works fine. i wonder if it's something to do with electron-prebuilt? i already have v0.36.0 but i see this package pulls in v0.35.4. thanks a lot!

**Comment by nodaguti** [comment]
Thank you for reporting an issue!
Your guess is right, updating electron-prebuilt to v0.36.0 and electron-mocha to 0.7.0 resolved this issue.
(In fact the renderer-side tests for this plugin had [some hacks to workaround the freezing](https://github.com/nodaguti/gulp-electron-mocha/commit/42353cd6afdce3ad0abe20d5348de2936c6ccff6), which were totally removed in v1.1.0)
Could you try v1.1.0 of gulp-electron-mocha? Thank you so much!

**Comment by nodaguti** [comment]
I'd like to close this issue.
If you encounter any troubles, please reopen this issue or file it as another issue.
Thanks a lot!
