### ISSUE TITLE
Please consider handing over admin privileges of this repo

### ISSUE THREAD

**Issue by ngprasad** [nodaguti/gulp-electron-mocha#44]
@nodaguti If you are not maintaining this repo could you please consider handing over the admin privileges to someone else who can maintain this repo. There have been a lot of PR's that will need to be reviewed and merged into this repo. For example the updates to electron-mocha is one and everyone is waiting for them to get merged.

Thanks for understanding,
Nischal

**Comment by nodaguti** [comment]
Sorry so much for being inactive for such a long time.

Today I updated all dependencies and set up greenkeeper-keeper to merge greenkeeper's pull requests automatically if there is no problem, so there should be a little chance to fall behind the stream and stick to outdated packages any more.

I see your concerns but I'd like to maintain this repo in future as until now. I'm very sorry again for keeping you waited and thank you for having been patient.
