### ISSUE TITLE
Not compatible with electron v1.0

### ISSUE THREAD

**Issue by ngprasad** [nodaguti/gulp-electron-mocha#8]
I noticed that gulp-electron-mocha is using electron-mocha 0.7.0 which is not compatible with Electron v1.0.0. This was added in electron-mocha v1.3.0. So gulp-electron-mocha needs to use the latest version of electron-mocha for compatibility.

**Comment by mrmlnc** [comment]
@nodaguti ping or fork ? :smiley:

**Comment by nodaguti** [comment]
I'm so sorry for the delay in working this issue.
I updated all dependencies and published it as v1.2.1.
If you find any problems, please let me know.

Thank you for reporting!
